import math
from collections import Counter
import numpy as np
from scapy.all import PcapReader, DNS, DNSQR, IP, IPv6

def calculate_shannon_entropy(s: str) -> float:
    """Calculates the Shannon entropy of a given string (e.g., domain name)."""
    if not s:
        return 0.0
    probabilities = [n_x / len(s) for x, n_x in Counter(s).items()]
    entropy = -sum(p * math.log2(p) for p in probabilities)
    return entropy

def tokenize_domain(s: str, max_len: int = 100) -> list:
    """
    Basic character tokenization for the L2 Transformer.
    Converts a domain string into a list of ASCII integers padded to max_len.
    """
    if not s:
        return [0] * max_len
    tokens = [ord(c) for c in s[:max_len]]
    if len(tokens) < max_len:
        tokens.extend([0] * (max_len - len(tokens)))
    return tokens

def calculate_window_stats(window_packets: list) -> dict:
    """
    Calculates window-level statistical aggregations for L1 XGBoost.
    Expects a list of dictionaries, each representing a packet with keys:
    - 'timestamp' (float: seconds)
    - 'domain' (str)
    - 'length' (int: bytes)
    """
    if not window_packets:
        return {
            'entropy_mean': 0.0, 'entropy_std': 0.0,
            'bytes_mean': 0.0, 'bytes_sum': 0.0,
            'iat_mean': 0.0, 'iat_std': 0.0,
            'packet_count': 0
        }
    
    entropies = []
    lengths = []
    timestamps = []
    
    for pkt in window_packets:
        domain = pkt.get('domain', '')
        entropies.append(calculate_shannon_entropy(domain))
        lengths.append(pkt.get('length', 0))
        timestamps.append(pkt.get('timestamp', 0.0))
        
    entropies = np.array(entropies)
    lengths = np.array(lengths)
    # Sort by timestamp to handle out-of-order packets within
    # PCAPs generated by mergecap or multi-interface captures.
    timestamps = np.array(timestamps)
    timestamps = np.sort(timestamps)
    
    # Inter-Arrival Time (IAT)
    if len(timestamps) > 1:
        iats = np.diff(timestamps)
        iat_mean = float(np.mean(iats))
        iat_std = float(np.std(iats))
    else:
        iat_mean = 0.0
        iat_std = 0.0
        
    return {
        'entropy_mean': float(np.mean(entropies)),
        'entropy_std': float(np.std(entropies)),
        'bytes_mean': float(np.mean(lengths)),
        'bytes_sum': float(np.sum(lengths)),
        'iat_mean': iat_mean,
        'iat_std': iat_std,
        'packet_count': len(window_packets)
    }

def extract_dns_features(packet):
    """Extrae características básicas de un paquete DNS de Scapy."""
    if packet.haslayer(DNS) and packet.haslayer(DNSQR):
        if packet.haslayer(IP):
            src_ip = packet[IP].src
        elif packet.haslayer(IPv6):
            src_ip = packet[IPv6].src
        else:
            return None
        
        try:
            domain = packet[DNSQR].qname.decode('utf-8', errors='ignore')
            if domain.endswith('.'):
                domain = domain[:-1]
        except Exception:
            domain = ''
            
        return {
            'timestamp': float(packet.time),
            'src_ip': src_ip,
            'domain': domain,
            'length': len(packet)
        }
    return None

def process_pcap(pcap_path: str, max_packets_per_window: int = 10, timeout_sec: float = 5.0) -> list:
    """Procesa un archivo PCAP y genera ventanas agrupadas por source_ip."""
    windows = []
    current_windows = {}
    
    print(f"Leyendo: {pcap_path} ...")
    try:
        for packet in PcapReader(pcap_path):
            feat = extract_dns_features(packet)
            if not feat:
                continue
                
            src_ip = feat['src_ip']
            timestamp = feat['timestamp']
            
            if src_ip not in current_windows:
                current_windows[src_ip] = {'packets': [], 'last_time': timestamp}
                
            # Timeout
            if timestamp - current_windows[src_ip]['last_time'] > timeout_sec:
                if len(current_windows[src_ip]['packets']) > 0:
                    windows.append(current_windows[src_ip]['packets'])
                current_windows[src_ip] = {'packets': [], 'last_time': timestamp}
                
            current_windows[src_ip]['packets'].append(feat)
            current_windows[src_ip]['last_time'] = timestamp
            
            # Límite de paquetes
            if len(current_windows[src_ip]['packets']) >= max_packets_per_window:
                windows.append(current_windows[src_ip]['packets'])
                current_windows[src_ip] = {'packets': [], 'last_time': timestamp}
                
        # Flush the remaining packets
        for src_ip, w_data in current_windows.items():
            if len(w_data['packets']) > 0:
                windows.append(w_data['packets'])
                
    except Exception as e:
        print(f"Error procesando {pcap_path}: {e}")
        
    return windows
